<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250223202307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, name_id INT NOT NULL, template_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9474526C71179CD6 ON comment (name_id)');
        $this->addSql('CREATE INDEX IDX_9474526C5DA0FB8 ON comment (template_id)');
        $this->addSql('CREATE TABLE form_submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, answer TEXT NOT NULL, submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, template_id INT NOT NULL, question_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D2C216675DA0FB8 ON form_submission (template_id)');
        $this->addSql('CREATE INDEX IDX_D2C216671E27F6BF ON form_submission (question_id)');
        $this->addSql('CREATE INDEX IDX_D2C21667A76ED395 ON form_submission (user_id)');
        $this->addSql('CREATE TABLE likes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, template_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_49CA4E7DA76ED395 ON likes (user_id)');
        $this->addSql('CREATE INDEX IDX_49CA4E7D5DA0FB8 ON likes (template_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_user_template ON likes (user_id, template_id)');
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, type VARCHAR(50) NOT NULL, show_in_table BOOLEAN NOT NULL, position INT NOT NULL, template_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B6F7494E5DA0FB8 ON question (template_id)');
        $this->addSql('CREATE TABLE registration (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_62A8A7A7E7927C74 ON registration (email)');
        $this->addSql('CREATE TABLE template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(10) DEFAULT \'public\' NOT NULL, tags JSON DEFAULT \'[]\' NOT NULL, author_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_97601F83F675F31B ON template (author_id)');
        $this->addSql('CREATE INDEX idx_created_at ON template (created_at)');
        $this->addSql('CREATE INDEX idx_status ON template (status)');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C71179CD6 FOREIGN KEY (name_id) REFERENCES registration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C5DA0FB8 FOREIGN KEY (template_id) REFERENCES template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_submission ADD CONSTRAINT FK_D2C216675DA0FB8 FOREIGN KEY (template_id) REFERENCES template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_submission ADD CONSTRAINT FK_D2C216671E27F6BF FOREIGN KEY (question_id) REFERENCES question (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE form_submission ADD CONSTRAINT FK_D2C21667A76ED395 FOREIGN KEY (user_id) REFERENCES registration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT FK_49CA4E7DA76ED395 FOREIGN KEY (user_id) REFERENCES registration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE likes ADD CONSTRAINT FK_49CA4E7D5DA0FB8 FOREIGN KEY (template_id) REFERENCES template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E5DA0FB8 FOREIGN KEY (template_id) REFERENCES template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE template ADD CONSTRAINT FK_97601F83F675F31B FOREIGN KEY (author_id) REFERENCES registration (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C71179CD6');
        $this->addSql('ALTER TABLE comment DROP CONSTRAINT FK_9474526C5DA0FB8');
        $this->addSql('ALTER TABLE form_submission DROP CONSTRAINT FK_D2C216675DA0FB8');
        $this->addSql('ALTER TABLE form_submission DROP CONSTRAINT FK_D2C216671E27F6BF');
        $this->addSql('ALTER TABLE form_submission DROP CONSTRAINT FK_D2C21667A76ED395');
        $this->addSql('ALTER TABLE likes DROP CONSTRAINT FK_49CA4E7DA76ED395');
        $this->addSql('ALTER TABLE likes DROP CONSTRAINT FK_49CA4E7D5DA0FB8');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E5DA0FB8');
        $this->addSql('ALTER TABLE template DROP CONSTRAINT FK_97601F83F675F31B');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE form_submission');
        $this->addSql('DROP TABLE likes');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE registration');
        $this->addSql('DROP TABLE template');
    }
}
